{% set python_min = "3.10" %}
{% set name = "nvidia-modulus" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/modulus/archive/refs/tags/v0.7.0.tar.gz
  sha256: edd94cbf713d3e26d6fa13738b0241cb8e3464e5f3d0b3d46d98a24cb27d0d2c

build:
  noarch: python
  script:
    - sed -i.bak '/nvidia_dali_cuda120/d' pyproject.toml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=2.0.0
    - numpy >=1.22.4,<1.25
    - xarray >=2023.1.0
    - zarr >=2.14.2
    - fsspec >=2023.1.0
    - s3fs >=2023.5.0
    - nvidia-dali-python >=1.35.0
    - setuptools >=67.6.0
    - certifi >=2023.7.22
    - pytz >=2023.3
    - treelib >=1.2.5
    - tqdm >=4.60.0
    - nvtx >=0.2.8
    - onnx >=1.14.0
    - timm >=0.9.12
    - importlib-metadata

test:
  imports:
    - modulus
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NVIDIA/modulus
  summary: A deep learning framework for AI-driven multi-physics systems
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
